version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "develop"
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "dependencies"
